-- se já existir um database chamado dbaluno2, apagar
DROP DATABASE IF EXISTS DBALUNO2;

-- criar database e table
CREATE DATABASE DBALUNO2;
USE DBALUNO2;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL AUTO_INCREMENT
	, NOME VARCHAR(20) NOT NULL
	, SEXO CHAR(1)
	, IDADE INT
	, CIDADE VARCHAR(20)
    , PRIMARY KEY (IDALUNO)
);

-- inserts na table
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('ANDERSON', 17, 'M','PALHOCA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('CESAR', 21, 'M', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('DANIEL', 19, 'M', 'PALHOCA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('DIEGO', 19, 'M', 'BLUMENAU');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('EDUARDO', 20, 'M', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('GABRIEL', 19, 'M', 'TUBARAO');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('JOAO', 18, 'M', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('LEONARDO', 19, 'M', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('LUCAS', 20, 'M', 'BLUMENAU');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('PRISCILA', 19, 'F', 'PALHOÇA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('RENATA', 21, 'F', 'TUBARAO');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('MARIA', 22, 'F', 'BLUMENAU');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('TANIA', 19, 'F', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('CARLOS', 22, 'M', 'TUBARAO');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('JOSE', 19, 'M', 'PALHOCA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('MARISA', 19, 'F', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('AMANDA', 20, 'F', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('JOANA', 19, 'F', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('ALICE', 21, 'F', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('TADEU', 18, 'M', 'TUBARAO');

-- selects 
SELECT * FROM ALUNO WHERE SEXO = 'M';
SELECT * FROM ALUNO WHERE IDADE = 19;
SELECT * FROM ALUNO WHERE NOME LIKE  "D%";
SELECT * FROM ALUNO where idade >=20 and idade <= 22;
SELECT * FROM ALUNO where cidade is null;
SELECT * FROM ALUNO WHERE CIDADE = "BLUMENAU";
SELECT * FROM ALUNO WHERE IDADE <> 18;
SELECT * FROM ALUNO WHERE NOME LIKE "%RI%";
SELECT * FROM ALUNO WHERE SEXO = 'M' AND IDADE < 20;
SELECT * FROM ALUNO WHERE (SEXO = 'F' AND IDADE > 20) OR (SEXO = 'M' AND IDADE > 17);
SELECT * FROM ALUNO WHERE NOME LIKE "%A%" AND NOME LIKE "%R%";
SELECT NOME, IDADE FROM ALUNO WHERE SEXO = 'F';
SELECT IDALUNO FROM ALUNO WHERE CIDADE = "BLUMENAU";
SELECT NOME, CIDADE FROM ALUNO WHERE IDADE<18;
SELECT NOME, CIDADE FROM ALUNO WHERE IDADE >=15 AND IDADE <= 18 AND CIDADE <> "PALHOCA";
SELECT CIDADE FROM ALUNO WHERE CIDADE <> "NULL"; 
SELECT NOME FROM ALUNO WHERE (IDADE = 18 AND CIDADE = "PALHOCA") OR (IDADE = 17 AND CIDADE = "SAO JOSE");
SELECT NOME FROM ALUNO WHERE SEXO = 'M' AND CIDADE = "TUBARAO" AND IDADE >=18 AND IDADE <= 25;
SELECT NOME, IDADE FROM ALUNO ORDER BY IDADE;
SELECT IDALUNO, NOME FROM ALUNO ORDER BY NOME DESC;
SELECT * FROM ALUNO ORDER BY IDADE DESC, NOME ASC; 
SELECT * FROM ALUNO ORDER BY SEXO, NOME;


